name: Awakenmedia
favicon: null
layout_spectrum: 0.75638
typography_spectrum: 0.85306
title: Awaken Media
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fd9427'
    - '#87d92a'
    - '#093796'
    - '#990b29'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
